<script src="<?=$us_url_root?>assets/js/vendor/bootstrap.bundle.min.js"></script>
<script src="<?=$us_url_root?>assets/js/vendor/jquery-3.7.1.min.js"></script>
<script src="<?=$us_url_root?>assets/js/vendor/swiper-bundle.min.js"></script>
<script src="<?=$us_url_root?>assets/js/swiper-script.js"></script>
<script src="<?=$us_url_root?>assets/js/submit-form.js"></script>
<script src="<?=$us_url_root?>assets/js/vendor/isotope.pkgd.min.js"></script>
<script src="<?=$us_url_root?>assets/js/vendor/fslightbox.js"></script>
<script src="<?=$us_url_root?>assets/js/masonry.js"></script>
<script src="<?=$us_url_root?>assets/js/vendor/datatables.min.js"></script>
<script src="<?=$us_url_root?>assets/js/script.js"></script>
